.PHONY: clean All

All:
	@echo "----------Building project:[ Pass_By_Reference - Debug ]----------"
	@cd "Pass_By_Reference" && "$(MAKE)" -f  "Pass_By_Reference.mk"
clean:
	@echo "----------Cleaning project:[ Pass_By_Reference - Debug ]----------"
	@cd "Pass_By_Reference" && "$(MAKE)" -f  "Pass_By_Reference.mk" clean
