.PHONY: clean All

All:
	@echo "----------Building project:[ Overloading_Function - Debug ]----------"
	@cd "Overloading_Function" && "$(MAKE)" -f  "Overloading_Function.mk"
clean:
	@echo "----------Cleaning project:[ Overloading_Function - Debug ]----------"
	@cd "Overloading_Function" && "$(MAKE)" -f  "Overloading_Function.mk" clean
