.PHONY: clean All

All:
	@echo "----------Building project:[ HowFunctionCallWork - Debug ]----------"
	@cd "HowFunctionCallWork" && "$(MAKE)" -f  "HowFunctionCallWork.mk"
clean:
	@echo "----------Cleaning project:[ HowFunctionCallWork - Debug ]----------"
	@cd "HowFunctionCallWork" && "$(MAKE)" -f  "HowFunctionCallWork.mk" clean
