.PHONY: clean All

All:
	@echo "----------Building project:[ Range-based_For_Loop - Debug ]----------"
	@cd "Range-based_For_Loop" && "$(MAKE)" -f  "Range-based_For_Loop.mk"
clean:
	@echo "----------Cleaning project:[ Range-based_For_Loop - Debug ]----------"
	@cd "Range-based_For_Loop" && "$(MAKE)" -f  "Range-based_For_Loop.mk" clean
