.PHONY: clean All

All:
	@echo "----------Building project:[ StaticClassMember - Debug ]----------"
	@cd "StaticClassMember" && "$(MAKE)" -f  "StaticClassMember.mk"
clean:
	@echo "----------Cleaning project:[ StaticClassMember - Debug ]----------"
	@cd "StaticClassMember" && "$(MAKE)" -f  "StaticClassMember.mk" clean
