/*

The default constructor
+ Does not expect any arguments
Also called the no-args constructor
+ If you write no constructors at all for a class
C++ will generate a default constructor that does nothing
+ Called when you instantiate a new object with no argument

*/

#include <iostream>

using namespace std;

/* Use default constructor that creates objects with no initialization information
class Account
{
private:
	string name;
	double balance;
public:
	bool withdraw(double amount);
	bool deposit(double amount);
};
*/

/* User defined no-args constructor
class Account
{
private:
	string name;
	double balance;
public:
	Account()
	{
		name = "None";
		balance = 0.0;
	}
	bool withdraw(double amount);
	bool deposit(double amount);
};
*/

/* Account - no default constructor 
When we define a constructor for our class -> C++ will not generate the no args default constructor automatically
If still need it, then must explicitly define it ourselves
If you have code that creates objects with no initialization information, then code will no longer compile as the default
constructor is no longer generated by C++

class Account
{
private:
	string name;
	double balance;
public:
	Account(string name_val, double bal)
	{
		name = name_val;
		balance = bal;
	}
	bool withdraw(double amount);
	bool deposit(double amount);
};

Account frank_account; // ERROR
Account *mary_account = new Account; // ERROR
Account bill_account {"Bill", 15000.0}; //OK
*/

int main()
{
	cout << "Default Template!" << endl; 
	return 0;
}
