.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_Assignment_LetterPyramid - Debug ]----------"
	@cd "Challenge_Assignment_LetterPyramid" && "$(MAKE)" -f  "Challenge_Assignment_LetterPyramid.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_Assignment_LetterPyramid - Debug ]----------"
	@cd "Challenge_Assignment_LetterPyramid" && "$(MAKE)" -f  "Challenge_Assignment_LetterPyramid.mk" clean
