.PHONY: clean All

All:
	@echo "----------Building project:[ WorkingWithCppString - Debug ]----------"
	@cd "WorkingWithCppString" && "$(MAKE)" -f  "WorkingWithCppString.mk"
clean:
	@echo "----------Cleaning project:[ WorkingWithCppString - Debug ]----------"
	@cd "WorkingWithCppString" && "$(MAKE)" -f  "WorkingWithCppString.mk" clean
