.PHONY: clean All

All:
	@echo "----------Building project:[ C_StyleStrings_Practice - Debug ]----------"
	@cd "C_StyleStrings_Practice" && "$(MAKE)" -f  "C_StyleStrings_Practice.mk"
clean:
	@echo "----------Cleaning project:[ C_StyleStrings_Practice - Debug ]----------"
	@cd "C_StyleStrings_Practice" && "$(MAKE)" -f  "C_StyleStrings_Practice.mk" clean
