.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge_Section4 - Debug ]----------"
	@cd "Challenge_Section4" && "$(MAKE)" -f  "Challenge_Section4.mk"
clean:
	@echo "----------Cleaning project:[ Challenge_Section4 - Debug ]----------"
	@cd "Challenge_Section4" && "$(MAKE)" -f  "Challenge_Section4.mk" clean
