.PHONY: clean All

All:
	@echo "----------Building project:[ IncreAndDecreOperator - Debug ]----------"
	@cd "IncreAndDecreOperator" && "$(MAKE)" -f  "IncreAndDecreOperator.mk"
clean:
	@echo "----------Cleaning project:[ IncreAndDecreOperator - Debug ]----------"
	@cd "IncreAndDecreOperator" && "$(MAKE)" -f  "IncreAndDecreOperator.mk" clean
