.PHONY: clean All

All:
	@echo "----------Building project:[ Declaring_Initialzing_Array - Debug ]----------"
	@cd "Declaring_Initialzing_Array" && "$(MAKE)" -f  "Declaring_Initialzing_Array.mk"
clean:
	@echo "----------Cleaning project:[ Declaring_Initialzing_Array - Debug ]----------"
	@cd "Declaring_Initialzing_Array" && "$(MAKE)" -f  "Declaring_Initialzing_Array.mk" clean
