.PHONY: clean All

All:
	@echo "----------Building project:[ Access_and_modify_elements - Debug ]----------"
	@cd "Access_and_modify_elements" && "$(MAKE)" -f  "Access_and_modify_elements.mk"
clean:
	@echo "----------Cleaning project:[ Access_and_modify_elements - Debug ]----------"
	@cd "Access_and_modify_elements" && "$(MAKE)" -f  "Access_and_modify_elements.mk" clean
