.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeSection - Debug ]----------"
	@cd "ChallengeSection" && "$(MAKE)" -f  "ChallengeSection.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeSection - Debug ]----------"
	@cd "ChallengeSection" && "$(MAKE)" -f  "ChallengeSection.mk" clean
